### ISSUE TITLE
Cut off at 0° lon (and maybe other bboxes?)

### ISSUE THREAD

**Issue by mmd-osm** [tyrasd/osm-tile-access-log-viewer#2]
I noticed some strange cut off at 0° lon, where only data on the east part is shown on the map. Tried both _tiles-2016-09-01.txt_ and _tiles-2016-09-04.txt_ . I'm not sure if the input data is bad or if there's some issue in the visualization.

Also, I found it somewhat strange that larger rectangular areas with lots of activity on zoom level 6 don't show up at all in zoom level 7. That doesn't seem to be very logical to me, but again the input data might be strange.

Example: Zoom level 6, center of map in Berlin, Germany on Sep 4th 2016. : 
- when zooming in from level 6 to 7, the area east of Nuremberg to the Eastern border of Poland is shown without any hits.
- then again zooming in to level 8, Berlin is shown again, but Hannover completely vanishes. 

![cut](https://cloud.githubusercontent.com/assets/5842757/18271846/abbd27de-7434-11e6-8aa6-e30a7f0dc1ff.png)

**Comment by tyrasd** [comment]
The data looks fine to me. And I can't confirm the issue with the two mentioned files here…
But this sounds very much like as if one of the rendering threads has crashed or didn't load its data properly.
Which browser did you use?
Do you see any error messages in the javascript console (you probably have to scroll all the way to the top to find any – there should be lots of "normal" debugging/timing messages)?

**Comment by mmd-osm** [comment]
I tried both Chrome Version 51.0.2704.106 (64-bit) and Firefox 48.0 on Ubuntu 16.04 with the same result. Javascript console doesn't show anything exciting when loading a file:

read file: 200.688ms
parser.js:33 parse data: 981.948ms
parser.js:48 send data: 62.365ms
index.js:22 parse data by worker: 1046.275ms
worker.js:27 load data: 0.596ms
worker.js:31 build indices: 0.344ms
worker.js:51 search data: 0.363ms
worker.js:72 render tile: 0.683ms
worker.js:79 send data: 1.778ms
worker.js:51 search data: 0.275ms
worker.js:27 load data: 0.676ms
worker.js:27 load data: 0.744ms
worker.js:31 build indices: 0.362ms
worker.js:31 build indices: 0.575ms
worker.js:51 search data: 0.389ms
worker.js:72 render tile: 1.692ms
worker.js:51 search data: 0.393ms
worker.js:72 render tile: 0.727ms
worker.js:27 load data: 0.655ms
worker.js:31 build indices: 0.389ms
worker.js:79 send data: 3.368ms
worker.js:79 send data: 2.781ms
worker.js:51 search data: 0.013ms
worker.js:51 search data: 1.635ms
worker.js:51 search data: 0.472ms
worker.js:72 render tile: 5.062ms
worker.js:72 render tile: 0.918ms
worker.js:72 render tile: 4.245ms
worker.js:79 send data: 3.312ms
worker.js:51 search data: 0.012ms
worker.js:72 render tile: 4.800ms
worker.js:79 send data: 6.654ms
worker.js:51 search data: 0.557ms
worker.js:79 send data: 9.423ms
worker.js:51 search data: 0.268ms
worker.js:79 send data: 5.171ms
worker.js:51 search data: 0.012ms
worker.js:72 render tile: 3.436ms
worker.js:72 render tile: 8.714ms
worker.js:72 render tile: 3.367ms
worker.js:72 render tile: 6.378ms
worker.js:79 send data: 1.060ms
worker.js:51 search data: 0.013ms
worker.js:72 render tile: 0.207ms
worker.js:79 send data: 1.235ms
worker.js:51 search data: 0.011ms
worker.js:72 render tile: 0.749ms
worker.js:79 send data: 3.353ms
worker.js:51 search data: 0.011ms
worker.js:72 render tile: 4.845ms
worker.js:79 send data: 7.380ms
worker.js:51 search data: 0.011ms
worker.js:79 send data: 6.170ms
worker.js:51 search data: 0.013ms
worker.js:72 render tile: 0.204ms
worker.js:72 render tile: 1.057ms
worker.js:79 send data: 8.175ms
worker.js:79 send data: 1.550ms
worker.js:79 send data: 3.101ms
worker.js:51 search data: 0.013ms
worker.js:79 send data: 2.171ms
worker.js:51 search data: 0.013ms
worker.js:72 render tile: 0.674ms
worker.js:72 render tile: 4.166ms
worker.js:79 send data: 4.297ms
worker.js:51 search data: 0.018ms
worker.js:72 render tile: 0.214ms
worker.js:79 send data: 1.478ms
worker.js:51 search data: 0.015ms
worker.js:72 render tile: 0.225ms
worker.js:79 send data: 1.298ms
worker.js:79 send data: 5.123ms
worker.js:27 load data: 358.226ms
worker.js:27 load data: 411.649ms
worker.js:27 load data: 489.952ms
worker.js:27 load data: 494.265ms
worker.js:31 build indices: 1398.314ms
worker.js:51 search data: 6.576ms
worker.js:72 render tile: 3.094ms
worker.js:79 send data: 3.770ms
worker.js:51 search data: 12.624ms
worker.js:72 render tile: 2.739ms
worker.js:79 send data: 4.317ms
worker.js:51 search data: 1.989ms
worker.js:72 render tile: 0.793ms
worker.js:79 send data: 3.956ms
worker.js:51 search data: 18.928ms
worker.js:72 render tile: 3.296ms
worker.js:79 send data: 3.362ms
worker.js:51 search data: 0.193ms
worker.js:72 render tile: 0.717ms
worker.js:79 send data: 4.706ms
worker.js:31 build indices: 1806.300ms
worker.js:51 search data: 5.643ms
worker.js:72 render tile: 4.936ms
worker.js:79 send data: 3.851ms
worker.js:51 search data: 1.136ms
worker.js:31 build indices: 1907.924ms
worker.js:51 search data: 3.723ms
worker.js:72 render tile: 2.671ms
worker.js:72 render tile: 17.249ms
worker.js:79 send data: 3.731ms
worker.js:51 search data: 1.108ms
worker.js:72 render tile: 0.523ms
worker.js:79 send data: 3.799ms
worker.js:79 send data: 8.092ms
worker.js:51 search data: 8.689ms
worker.js:72 render tile: 2.067ms
worker.js:79 send data: 3.309ms
worker.js:51 search data: 0.210ms
worker.js:72 render tile: 0.535ms
worker.js:79 send data: 3.152ms
worker.js:51 search data: 6.504ms
worker.js:72 render tile: 1.410ms
worker.js:79 send data: 4.112ms
worker.js:51 search data: 56.368ms
worker.js:72 render tile: 8.463ms
worker.js:79 send data: 8.407ms
worker.js:51 search data: 35.495ms
worker.js:72 render tile: 5.389ms
worker.js:79 send data: 3.607ms
worker.js:51 search data: 0.627ms
worker.js:72 render tile: 0.297ms
worker.js:79 send data: 4.151ms
worker.js:31 build indices: 2021.268ms
worker.js:51 search data: 4.446ms
worker.js:72 render tile: 2.787ms
worker.js:79 send data: 4.269ms
worker.js:51 search data: 27.396ms
worker.js:72 render tile: 5.683ms
worker.js:79 send data: 5.058ms
worker.js:51 search data: 0.146ms
worker.js:72 render tile: 1.180ms
worker.js:79 send data: 3.946ms
worker.js:51 search data: 37.579ms
worker.js:72 render tile: 4.521ms
worker.js:79 send data: 3.904ms
worker.js:51 search data: 0.552ms
worker.js:72 render tile: 0.502ms
worker.js:79 send data: 3.389ms

sha256sum tiles-2016-09-04.txt 
066261459cfdf3d928621c4f62f960e8f13736a2281604a1e0b108e8a4954aba  tiles-2016-09-04.txt

**Comment by tyrasd** [comment]
yep, I got the same sha256 checksum.

ok. by manually setting concurrency to 8 parallel rendering threads, I'm seeing the problem as well (only got a 4-code CPU here, so I didn't see it personally). investigating.

**Comment by tyrasd** [comment]
oops, forgot to replace a hardcoded concurrency value with the proper number of workers. :blush:

**Comment by mmd-osm** [comment]
Thanks, looking much better now!

Still I wonder where those  differences come from on different zoom levels. In the example below, pretty much everything in Paris disappears when moving from level 10 to 11. I'm sure there's still some data at level 11.

Again September 4th, 2016:

http://osm-tile-access-log-viewer.raifer.tech/#10/48.9049/2.3518
![yd1](https://cloud.githubusercontent.com/assets/5842757/18280358/13512c32-7459-11e6-80c4-23e4ef4b92d2.png)

vs.
http://osm-tile-access-log-viewer.raifer.tech/#11/48.8740/2.3535
![yd2](https://cloud.githubusercontent.com/assets/5842757/18280367/188267c0-7459-11e6-917f-0d8c5ed2f4ff.png)

**Comment by tyrasd** [comment]
No, that's actually in the data!

Zoom 11 in the visualization corresponds to zoom level 19 (the highest) on osm.org, which is far less frequently requested than zoom 18 one level up. That's probably because most apps and websites using osm tiles still use level 18 as their `maxZoom` setting (probably because that's the default in many libraries such as leaflet.js). Also note that tiles with less than 10 accesses are not included in the logs, and therefore don't show up in the viz which makes tiles on the high zoom levels (roughly speaking 4 times) less likely to show up.

**Comment by mmd-osm** [comment]
Ah, thanks for the explanation! It wasn't obvious to me, how the zoom level in the visualization relates to the zoom level on osm.org.

**Comment by tyrasd** [comment]
that's quite understandable. I've now added an on-click popup which shows which actual tile each pixel represents:

![selection_082](https://cloud.githubusercontent.com/assets/1927298/18310354/24c60596-74fe-11e6-889b-c567a336f9c8.png)
